#pragma config(Motor,  port2,           WheelR,        tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           WheelL,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           DnaMechanism,  tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           ClampArm,      tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{
  motor[port3] = vexRT[Ch2];
  motor[port2] = vexRT[Ch3];
 	//motor[port5] = vexRT[Ch5];

 	if(vexRT[Btn5U] == 1) //Extend Up
  {
  motor[ClampArm] = 127;
  }
  else if(vexRT[Btn5D] == 1) //Retract Down
  {
  motor[ClampArm] = -127;
  }
  else
  {
  motor[ClampArm] = 0;

  if(vexRT[Btn6U] == 1) //Up
  {
  motor[DnaMechanism] = 127;
  }
  else if(vexRT[Btn6D] == 1) //Down
  {
  motor[DnaMechanism] = -127;
  }
  else
  {
  motor[DnaMechanism] = 0;
  }
}

}
}
