#pragma config(Motor,  port3,           WheelR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,           WheelL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ClimbArm,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           Scissors,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  bDisplayCompetitionStatusOnLcd = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Autonomous is 15 seconds
  // ..........................................................................

  // Remove this function call once you have "real" code.
  //AutonomousCodePlaceholderForTesting();
		//wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program

	// Move forward at full power for 3 seconds (extension function)
		/*motor[WheelR] = 80;		  // Motor on port2 is run at full (127) power forward
		motor[WheelL] = 127;		  // Motor on port3 is run at full (127) power forward
		wait1Msec(2500);			        // Robot runs previous code for 3000 milliseconds (3s) before moving on
		motor[WheelR] = 0;
		motor[WheelL] = 0;
		wait1Msec(250);
		motor[Scissors] = 127;
		wait1Msec(50);			        // Robot runs previous code to operate DnaMechanism
		motor[Scissors] = 0;		  // Motor on port5 is run at full (127) power forward
		wait1Msec(50);			        // Robot runs previous code to operate DnaMechanism
		motor[Scissors] = -127;
		wait1Msec(50);
		motor[Scissors] = 0;
		wait1Msec(50);
    motor[WheelR] = -80;
		motor[WheelL] = -127;
		wait1Msec(250);
		motor[WheelR] = 0;
		motor[WheelL] = 0;
		wait1Msec(250);
		return;
		//turn -90 degrees.   turns around 15 degrees for every 100 msec at 80 power
		motor[WheelR] = 80;		  // Motor on port2 is run at half  (80) power forward
		motor[WheelL] = -80;		  // Motor on port3 is run at half (-80) power reverse
		wait1Msec(530);			        // Robot runs previous code for 500 milliseconds (1/2s) before moving on
		motor[WheelR] = 0;
		motor[WheelL] = 0;
		wait1Msec(250);
		motor[WheelR] = 80;
		motor[WheelL] = 127;
		wait1Msec(3900);
		motor[WheelR] = 0;
		motor[WheelL] = 0;
		wait1Msec(250);

		//turn 90 degrees.
		motor[WheelR] = -80;
		motor[WheelL] = 80;
		wait1Msec(530);
		motor[WheelR] = 0;
		motor[WheelL] = 0;
		wait1Msec(250);

		motor[WheelR] = 80;
		motor[WheelL] = 127;
		wait1Msec(650);
		motor[WheelR] = 0;
		motor[WheelL] = 0;
		wait1Msec(250);

		motor[Scissors] = 127;
		wait1Msec(800);
		motor[Scissors] = 0;
		wait1Msec(50);
		motor[Scissors] = -127;
		wait1Msec(800);
		motor[Scissors] = 0;*/
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  Duration is 1:45   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................
 		motor[WheelR] = -vexRT[Ch2];
  	motor[WheelL] = -vexRT[Ch3];


 		if(vexRT[Btn5U] == 1) //Extend Up
  {
  		motor[Scissors] = 127;
  }
  	else if(vexRT[Btn5D] == 1) //Retract Down
  {
  		motor[Scissors] = -127;
  }
  	else
  {
  		motor[Scissors] = 0;

  	if(vexRT[Btn6U] == 1) //Up
  {
  		motor[ClimbArm] = 127;
  }
  	else if(vexRT[Btn6D] == 1) //Down
  {
  		motor[ClimbArm] = -127;
  }
  	else
  {
  	motor[ClimbArm] = 0;
  }
}

  }
}
